### ISSUE TITLE
Disabled attribute is not being applied to the dom for the back or next buttons.

### ISSUE THREAD

**Issue by AntiFish03** [bevacqua/rome#129]
I saw this in the css
```css
.rd-back[disabled],
.rd-next[disabled] {
  cursor: default;
}
```
but I have noticed that disabled never gets added as an attribute to the button.
